apiVersion: v1
kind: Service
metadata:
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:042850181621:certificate/b88c13c5-b530-4b70-9dbf-243d205209ff
  name: lb-service
spec:
  type: LoadBalancer
  selector:
    lb: external
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
